pipeline {
    agent any

    environment {
        BUILD_SERVER_IP = '172.31.42.3'
    }

    stages {
        stage('Cleanup and Clone Repository') {
            steps {
                script {
                    // Remove existing Day6 directory and clone the latest repo
                    sh "ssh ubuntu@${BUILD_SERVER_IP} 'rm -rf /home/ubuntu/Jenkins_devops && git clone https://github.com/krishna1369/Jenkins_devops.git /home/ubuntu/Jenkins_devops'"
                }
            }
        }

        stage('Build Docker images on Build Server') {
            steps {
                script {
                    // Execute Ansible playbook on Build Server
                    sh "ssh ubuntu@${BUILD_SERVER_IP} 'ansible-playbook /home/ubuntu/Jenkins_devops/Ansible/build.yaml'"
                }
            }
        }

        stage('Deploy Script on Deploy Server') {
            steps {
                script {
                    // Execute deployment playbook on Deploy Server
                    sh "ssh ubuntu@${BUILD_SERVER_IP} 'ansible-playbook /home/ubuntu/Jenkins_devops/Ansible/deploy.yaml'"
                }
            }
        }
    }
}
